%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\nxf63339\Documents\Differential Probe\Data acquisition\Tektronix\MATLAB data acquisition scripts\StoredData\3,3VIO_5,5VCC_50DUTY_1MHz_08-04-2020_12-04-25_CANH.csv
%
% Auto-generated by MATLAB on 04-Aug-2020 12:40:08

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Time", "Amplitude"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
CANH = readtable("C:\Users\nxf63339\Documents\Differential Probe\Data acquisition\Tektronix\MATLAB data acquisition scripts\StoredData\3,3VIO_5,5VCC_50DUTY_1MHz_08-04-2020_12-04-25_CANH.csv", opts);
CANL = readtable("C:\Users\nxf63339\Documents\Differential Probe\Data acquisition\Tektronix\MATLAB data acquisition scripts\StoredData\3,3VIO_5,5VCC_50DUTY_1MHz_08-04-2020_12-04-25_CANL.csv", opts);
VOUT = readtable("C:\Users\nxf63339\Documents\Differential Probe\Data acquisition\Tektronix\MATLAB data acquisition scripts\StoredData\3,3VIO_5,5VCC_50DUTY_1MHz_08-04-2020_12-04-25_VOUT.csv", opts);

VDIFF = [CANH.Time (CANH.Amplitude - CANL.Amplitude)];

%% Clear temporary variables
clear opts

%% Plot the data
hold on, grid on;
% plot(VIO3_3VCC5_5_DUTY50_1MHz_CANH.Time, VIO3_3VCC5_5_DUTY50_1MHz_CANH.Amplitude),

% plot(VIO3_3VCC5_5_DUTY50_1MHz_CANL.Time, VIO3_3VCC5_5_DUTY50_1MHz_CANL.Amplitude);
plot(CANH.Time, VOUT.Amplitude, 'magenta'); %-(VOUT.Amplitude(1) to compensate for an offset
% plot((VIO3_3VCC5_5_DUTY50_1MHz_CANH.Time), (VIO3_3VCC5_5_DUTY50_1MHz_CANH.Amplitude - VIO3_3VCC5_5_DUTY50_1MHz_CANL.Amplitude));
plot(CANH.Time, VDIFF(:,2), 'green');
legend('VOUT', 'VDIFF');